develop:
  mnemonic: sea total mirror fat opera swear fox history such assist picture snack
  shardToWrite: ELROND
  shardToExecute: BNB
  endpoint: https://coinweb-experimental-bitcoin-graphql-green.coinz.team/wallet

  bootstrapConfig:
    dataHasher: data_hasher_v2
    controller: controller_v2
    dependencies:
    - decompressor_v2
    - data_hasher

  replicateConfig: &prod_replicate
    replicator: replicant.cm v0.0.2
    replicas: 
    - shard: eth
      interpreters: 
      - data_hasher
      - data_hasher_v2
      - std_js_contract_v0
      templates:
      - jump-listener.cm v0.0.4
      instances: []
    - shard: btc
      interpreters: 
      - data_hasher
      - data_hasher_v2
      - std_js_contract_v0
      templates:
      - jump-listener.cm v0.0.4
      instances: []

  unsafe: true

  gitRemoteLockIndexRepo: git@gitlab.com:coinweb/cweb-dapp-index.git
  pathToIndexFile: .cweb-config/dapp-ecosystem.yaml
  pathToLockIndexFile: .dapp-ecosystem-lock.yaml
  pathToRawActionFile: ./.unfiltered-actions.yaml
  pathToFilteredActionFile: .actions.yaml
  packageRegistry: 'https://npm.coinweb.io'

production:
  mnemonic: sea total mirror fat opera swear fox history such assist picture snack
  shardToWrite: ELROND
  shardToExecute: BNB
  endpoint: https://api-cloud.coinweb.io/wallet

  bootstrapConfig:
    dataHasher: data_hasher_v2
    controller: controller_v2
    dependencies:
    - decompressor_v2
    - data_hasher

  replicateConfig: *prod_replicate

  unsafe: true

  gitRemoteLockIndexRepo: git@gitlab.com:coinweb/cweb-dapp-index.git
  pathToIndexFile: .cweb-config/dapp-ecosystem-prod.yaml
  pathToLockIndexFile: .dapp-ecosystem-lock-prod.yaml
  pathToRawActionFile: ./.unfiltered-actions-prod.yaml
  pathToFilteredActionFile: .actions-prod.yaml
  packageRegistry: 'https://npm.coinweb.io'

devnet:
  mnemonic: priority supply couple broccoli balcony sort flag keep original wrong pottery version
  shardToWrite: DEVNET_L1A
  shardToExecute: DEVNET_L1A
  endpoint: https://coinweb-experimental-bitcoin-graphql-devblue.coinhq.store/wallet

  bootstrapConfig:
    dataHasher: data_hasher_v2
    controller: controller_v2
    dependencies:
    - decompressor_v2
    - data_hasher

  replicateConfig: &dev_replicate
    replicator: replicant.cm v0.0.2
    replicas: 
    - shard: devb
      interpreters: 
      - data_hasher
      - data_hasher_v2
      - std_js_contract_v0
      templates:
      - jump-listener.cm v0.0.4
      instances: []
    - shard: tbtc
      interpreters: 
      - data_hasher
      - data_hasher_v2
      - std_js_contract_v0
      templates:
      - jump-listener.cm v0.0.4
      instances: []

  unsafe: true

  # gitRemoteLockIndexRepo: git@gitlab.com:coinweb/cweb-dapp-index.git
  pathToIndexFile: .cweb-config/dapp-ecosystem-devnet.yaml
  pathToLockIndexFile: .dapp-ecosystem-lock-devnet.yaml
  pathToRawActionFile: ./.unfiltered-actions-devnet.yaml
  pathToFilteredActionFile: .actions-devnet.yaml
  packageRegistry: 'https://npm.coinweb.io'

prod_demo:
  mnemonic: negative dog base document ring lesson veteran play code viable benefit turtle
  shardToWrite: ELROND
  shardToExecute: BNB
  endpoint: https://bitcoin-graphql-demo.coinhq.store/wallet

  bootstrapConfig:
    dataHasher: data_hasher_v2
    controller: controller_v2
    dependencies:
    - decompressor_v2
    - data_hasher

  replicateConfig: *dev_replicate

  unsafe: true

  gitRemoteLockIndexRepo: git@gitlab.com:coinweb/cweb-dapp-index.git
  pathToIndexFile: .cweb-config/dapp-ecosystem-prod-demo.yaml
  pathToLockIndexFile: .dapp-ecosystem-lock-prod-demo.yaml
  pathToRawActionFile: ./.unfiltered-actions-prod-demo.yaml
  pathToFilteredActionFile: .actions-prod-demo.yaml
  packageRegistry: 'https://npm.coinweb.io'

tests:
  mnemonic: priority supply couple broccoli balcony sort flag keep original wrong pottery version
  shardToWrite: DEVNET_L1A
  shardToExecute: DEVNET_L1A
  endpoint: https://api-devblue.coinhq.store/wallet

  bootstrapConfig:
    dataHasher: data_hasher_v2
    controller: controller_v2
    dependencies:
    - decompressor_v2
    - data_hasher

  replicateConfig: *dev_replicate

  unsafe: true

  gitRemoteLockIndexRepo: git@gitlab.com:coinweb/cweb-dapp-index.git
  pathToIndexFile: .cweb-config/dapp-ecosystem-devnet-blue.yaml
  pathToLockIndexFile: .dapp-ecosystem-lock-tests.yaml
  pathToRawActionFile: ./.unfiltered-actions-tests.yaml
  pathToFilteredActionFile: .actions-tests.yaml
  packageRegistry: 'https://npm.coinweb.io'
