{{- if and (.Values.service.enabled) (or (.Values.ingress.enabled) (not (hasKey .Values.ingress "enabled"))) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "sharedlabels" . | indent 4 }}
  annotations:
{{ include "ingress.annotations" . | indent 4 }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
{{- end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
{{- range $url := .Values.service.urls }}
    - {{ template "hostname" $url }}
{{- end }}
{{- end }}
{{- if not .Values.ingress.tls.useDefaultSecret }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "fullname" .)) }}
{{- end }}
  rules:
{{- range $url := .Values.service.urls }}
  - host: {{ template "hostname" $url }}
    http:
      paths:
      - path: {{ $.Values.ingress.path | default "/" | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "fullname" $ }}
            port:
              number: {{ $.Values.service.externalPort }}
{{- end }}
{{- end -}}
