export enum Key {
  CONTRACT_OWNER = 'CONTRACT_OWNER',
  MAKER_STATE = 'MAKER_STATE',
  MAKER_AVAILABLE_BALANCE = 'MAKER_AVAILABLE_BALANCE',
  ORDER_STATE = 'ORDER_STATE',
  ORDER_COLLATERAL = 'ORDER_COLLATERAL',
  ORDER_OWNER_INDEX = 'ORDER_OWNER_INDEX',
  ORDER_DATE_INDEX = 'ORDER_DATE_INDEX',
  ORDER_BEST_INDEX = 'ORDER_BEST_INDEX',
  ORDER_ACTIVE_INDEX = 'ORDER_ACTIVE_INDEX',
  ORDER_PENDING_INDEX = 'ORDER_PENDING_INDEX',
  ORDER_CLOSED_INDEX = 'ORDER_CLOSED_INDEX',
  REQUEST_STATE = 'REQUEST_STATE',
  REQUEST_FUNDS = 'REQUEST_FUNDS',
}

export enum ORDER_ACTIVITY_STATUS {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLING = 'CANCELLING',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum REQUEST_EXECUTION_STATUS {
  PENDING = 'PENDING',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
}

export enum PUBLIC_METHODS {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  CREATE_ORDER = 'CREATE_ORDER',
  CHANGE_ORDER = 'CHANGE_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  REQUEST_EXECUTION = 'REQUEST_EXECUTION',
  CHANGE_CONTRACT_OWNER = 'CHANGE_CONTRACT_OWNER',
  SEED = 'SEED',
}

export const FEE = {
  CREATE_ORDER: 50000n,
  CANCEL_ORDER: 50000n,
  DEPOSIT: 50000n,
  WITHDRAW: 50000n,
  HANDLE_EXECUTION_REQUEST: 50000n,
};
